layout: sidebar
style: light

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

projects:
  sort_by: pushed
  # sort_by options:
  #   - pushed
  #   - stars
  limit: 9
  exclude:
    archived: false
    forks: true
    projects:
     - docker-shiny-server-libssl

social_media:
  # behance: your_username
  # dribbble: your_username
  # facebook: your_username
  # hackerrank: your_username
  # instagram: your_username
  # keybase: your_username
  linkedin: victor-rodriguez-fernandez
  # mastodon: your_username
  # medium: your_username
  # stackoverflow: your_user_id
  # telegram: your_username
  twitter: vrodriguezf90
  # unsplash: your_username
  # vk: your_username
  # website: http://your_website_url
  # youtube: your_username
  scholar: P1yxTEsAAAAJ

topics:
  - name: Deep learning
    web_url: https://github.com/topics/deep-learning
    image_url: https://static.thenounproject.com/png/1705425-200.png

  - name: Time series
    web_url: https://github.com/topics/time-series
    image_url: https://static.thenounproject.com/png/2046072-200.png
